### ISSUE TITLE
Add defining tag groups

### ISSUE THREAD

**Issue by barrettMCW** [laviolette-lab/omero-ruletagger#12]
Requested [here](https://forum.image.sc/t/omero-ruletagger-attribute-based-tagging-utility/108836/3).

Maybe just add a top level `group` attribute?
```
- name: "FALSE"
  group: "ExampleTags"
  rules:
    - attribute_path: ["image", "roicount"]
      operation: lt
      value: 1
```

For our lab's rules, we can have slide and subject groups by refactoring the regex part.
